local style = require "core.style"
local common = require "core.common"

style.background = { common.color "#1c1b19" }
style.background2 = { common.color "#1c1b19" }
style.background3 = { common.color "#121212" }
--style.text = { common.color "#928374" }
style.text = { common.color "#baa67f" }
style.caret = { common.color "#baa67f" }
style.accent = { common.color "#ff5c8f" }
style.dim = { common.color "#918175" }
style.divider = { common.color "#262626" }
style.selection = { common.color "#262626" }
style.line_number = { common.color "#918175" }
style.line_number2 = { common.color "#baa67f" }
style.line_highlight = { common.color "#3a3a3a" }
style.scrollbar = { common.color "#918175" }
style.scrollbar2 = { common.color "#baa67f" }

style.syntax["normal"] = { common.color "#baa67f" }
style.syntax["symbol"] = { common.color "#baa67f" }
style.syntax["comment"] = { common.color "#918175" }
style.syntax["keyword"] = { common.color "#fb4934" }
style.syntax["keyword2"] = { common.color "#83a598" }
style.syntax["number"] = { common.color "#d3869b" }
style.syntax["literal"] = { common.color "#d3869b" }
style.syntax["string"] = { common.color "#b8bb26" }
style.syntax["operator"] = { common.color "#ebdbb2" }
style.syntax["function"] = { common.color "#8ec07c" }
