filetype: conf

detect:
    filename: "(\\.(conf)$|\\.(cfg)$)|\.c[o]?nf$""

rules:
    - constant.string:
        start: "\""
        end: "\""
        skip: "\\\\."
        rules:
            - constant.specialChar: "\\\\."

    - comment:
        start: "#"
        end: "$"
        rules:
            - todo: "(TODO|XXX|FIXME):?"
