version: "3.7"

networks:
  ihappennetwork:
    name: ihappen-network

services:
  pg:
    image: postgres:12.0
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d/
    networks:
      ihappennetwork:
        aliases: ["database"]
  migrate:
    image: migrate/migrate
    networks:
      - ihappennetwork
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable", "up"]
    links:
      - pg
  ih_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_PORT: ${API_PORT}
    depends_on:
      - pg
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - ihappennetwork
    env_file:
      - .env
    entrypoint: ["/bin/ihapp"]